export const SignIn = '/api/v1/auth/login'
export const SignUp = '/api/v1/auth/signup'
export const ForgotPassword = '/api/v1/auth/forgot-password'
export const ResetPassword = '/api/v1/auth/reset-password'
export const RefreshToken = '/api/v1/auth/refresh-token'
export const VerifyToken = '/api/v1/auth/verify-token/:token'

export const StartUpApplicationCreate = '/api/v1/company/application/create'
export const StartUpApplicationUpdate = '/api/v1/company/application/update'
export const StartUpApplicationList = '/api/v1/company/application/list'
export const StartUpApplicationGetById = '/api/v1/company/application/:id'
export const StartUpApplicationDelete = '/api/v1/company/application/create'

export const StartUpCompanyCreate = '/api/v1/company/create'
export const StartUpCompanyUpdate = '/api/v1/company/update'
export const StartUpCompanyList = '/api/v1/company/list'
export const StartUpCompanyGetByName = '/api/v1/company/by-name'
export const StartUpCompanyDeleteMultiple = '/api/v1/company/delete'
export const StartUpCompanyDelete = '/api/v1/company/delete/:id'
export const StartUpCompanyGetById = '/api/v1/company/:id'
export const StartUpCompanyGetCountByRegion = '/api/v1/company/list/count'
export const StartUpCompanyGetByIndustryId = '/api/v1/company/list/industry'
export const StartUpCompanyGetNews = '/api/v1/company/news'
export const StartUpCompanySummary = '/api/v1/company/summary'
export const StartUpCompanyCreateByExcel = '/api/v1/company/upload/excel'

export const CountryList = '/api/v1/country/list'

export const FileUploadCompany = '/api/v1/upload/:companyId'
export const GetFile = '/api/v1/upload/:filename'

export const FounderCreate = '/api/v1/founder/create'
export const FounderUpdate = '/api/v1/founder/update'
export const FounderList = '/api/v1/founder/list'
export const FounderDelete = '/api/v1/founder/delete/:id'
export const FounderDeleteMultiple = '/api/v1/founder/delete'
export const FounderGetAll = '/api/v1/founder/getAll'
export const FounderGetById = '/api/v1/founder/:id'

export const FundingCreate = '/api/v1/funding/create'
export const FundingUpdate = '/api/v1/funding/update'
export const FundingList = '/api/v1/funding/list'
export const FundingGetById = '/api/v1/funding/:id'
export const FundingDelete = '/api/v1/funding/delete/:id'

export const IndustryCreate = '/api/v1/industry/create'
export const IndustryUpdate = '/api/v1/industry/update'
export const IndustryDelete = '/api/v1/industry/delete/:id'
export const IndustryList = '/api/v1/industry/list'
export const IndustryGetById = '/api/v1/industry/:id'

export const RankingCreate = '/api/v1/ranking/create'
export const RankingGetById = '/api/v1/ranking/:id'
export const RankingUpdate = '/api/v1/ranking/:id'
export const RankingGetByCountryId = '/api/v1/ranking/by-country/:id'
export const RankingGetByCountryMain = '/api/v1/ranking/by-country/main'
export const RankingGetByRegionMain = '/api/v1/ranking/by-region/main'
export const RankingDelete = '/api/v1/ranking/delete/:id'
export const RankingList = '/api/v1/ranking/list'
export const RankingMain = '/api/v1/ranking/main'
